name: Test

on:
  - pull_request
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    needs:
      - test

    strategy:
      fail-fast: false
      matrix:
        platform:
          - chrome
          - firefox

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build:${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_REDIRECT_URI: ${{ secrets.TWITCH_REDIRECT_URI }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-artifact
          path: dist
